spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keepr
    username: keepr
    password: keepr_local
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
